version: '3.8'

services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=drunks'
      - 'MONGO_INITDB_ROOT_USERNAME=drunks'
      - 'MONGO_INITDB_ROOT_PASSWORD=sknurd'
    ports:
      - '27017:27017'
    volumes:
      - ./drunks-data:/data/db
